import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/providers/AuthProviders";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { ThemeToggler } from "@/components/core/ThemeToggler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeConfig = {
  colors: {
    primary: "#532cde",
    // You can add more colors here
    // secondary: "#22c55e",
    // accent: "#f59e0b"
  },
  radius: "0.75rem",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider config={themeConfig}>
          <AuthProvider>
            {/* Theme toggler positioned at top right */}
            <div className="fixed top-4 right-4 z-50">
              <ThemeToggler />
            </div>
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}